/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module add16_5 (
    input [15:0] a,
    input [15:0] b,
    input [5:0] alufn,
    output reg [15:0] out,
    output reg z,
    output reg v,
    output reg n
  );
  
  
  
  reg [15:0] tmpout;
  
  reg [15:0] tmpb;
  
  always @* begin
    z = 1'h0;
    v = 1'h0;
    n = 1'h0;
    
    case (alufn[0+1-:2])
      2'h0: begin
        tmpout = a + b;
        z = (tmpout == 16'h0000);
        v = ((a[15+0-:1] & b[15+0-:1] & !tmpout[15+0-:1]) | (!a[15+0-:1] & !b[15+0-:1] & tmpout[15+0-:1]));
        n = tmpout[15+0-:1];
      end
      2'h1: begin
        tmpb = b ^ {5'h10{alufn[0+0-:1]}};
        tmpout = a + tmpb + 1'h1;
        z = (tmpout == 16'h0000);
        v = ((a[15+0-:1] & tmpb[15+0-:1] & !tmpout[15+0-:1]) | (!a[15+0-:1] & !tmpb[15+0-:1] & tmpout[15+0-:1]));
        n = tmpout[15+0-:1];
      end
      2'h2: begin
        tmpout = a * b;
      end
      2'h3: begin
        tmpb = b ^ {5'h10{alufn[0+0-:1]}};
        tmpout = a + tmpb + 1'h1;
        z = (tmpout == 16'h0000);
        v = ((a[15+0-:1] & tmpb[15+0-:1] & !tmpout[15+0-:1]) | (!a[15+0-:1] & !tmpb[15+0-:1] & tmpout[15+0-:1]));
        n = tmpout[15+0-:1];
      end
      default: begin
        tmpout = 1'h0;
      end
    endcase
    out = tmpout;
  end
endmodule
