/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module au_top_0 (
    input clk,
    input rst_n,
    output reg [7:0] led,
    input usb_rx,
    output reg usb_tx,
    output reg [23:0] io_led,
    output reg [7:0] io_seg,
    output reg [3:0] io_sel,
    input [4:0] io_button,
    input [23:0] io_dip
  );
  
  
  
  reg rst;
  
  wire [16-1:0] M_manual_tester_out;
  reg [16-1:0] M_manual_tester_in;
  reg [2-1:0] M_manual_tester_switch;
  reg [6-1:0] M_manual_tester_alufn;
  manual_test_1 manual_tester (
    .clk(clk),
    .rst(rst),
    .in(M_manual_tester_in),
    .switch(M_manual_tester_switch),
    .alufn(M_manual_tester_alufn),
    .out(M_manual_tester_out)
  );
  wire [5-1:0] M_auto_tester_out;
  auto_test_2 auto_tester (
    .clk(clk),
    .rst(rst),
    .out(M_auto_tester_out)
  );
  
  wire [1-1:0] M_reset_cond_out;
  reg [1-1:0] M_reset_cond_in;
  reset_conditioner_3 reset_cond (
    .clk(clk),
    .in(M_reset_cond_in),
    .out(M_reset_cond_out)
  );
  
  always @* begin
    M_reset_cond_in = ~rst_n;
    rst = M_reset_cond_out;
    usb_tx = usb_rx;
    led = 8'h00;
    io_led = 24'h000000;
    io_seg = 8'hff;
    io_sel = 4'hf;
    M_manual_tester_alufn = io_dip[16+0+5-:6];
    M_manual_tester_switch = io_dip[16+6+1-:2];
    M_manual_tester_in = io_dip[0+15-:16];
    io_led[0+15-:16] = M_manual_tester_out;
    io_led[16+3+4-:5] = M_auto_tester_out;
  end
endmodule
