/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module manual_test_1 (
    input clk,
    input rst,
    input [15:0] in,
    input [1:0] switch,
    input [5:0] alufn,
    output reg [15:0] out
  );
  
  
  
  wire [16-1:0] M_alu16_out;
  wire [1-1:0] M_alu16_z;
  wire [1-1:0] M_alu16_v;
  wire [1-1:0] M_alu16_n;
  reg [16-1:0] M_alu16_a;
  reg [16-1:0] M_alu16_b;
  reg [6-1:0] M_alu16_alufn;
  alu_4 alu16 (
    .a(M_alu16_a),
    .b(M_alu16_b),
    .alufn(M_alu16_alufn),
    .out(M_alu16_out),
    .z(M_alu16_z),
    .v(M_alu16_v),
    .n(M_alu16_n)
  );
  
  localparam INPUTA_test = 2'd0;
  localparam INPUTB_test = 2'd1;
  localparam OUTPUT_test = 2'd2;
  
  reg [1:0] M_test_d, M_test_q = INPUTA_test;
  reg [15:0] M_inputa_d, M_inputa_q = 1'h0;
  reg [15:0] M_inputb_d, M_inputb_q = 1'h0;
  
  always @* begin
    M_test_d = M_test_q;
    M_inputb_d = M_inputb_q;
    M_inputa_d = M_inputa_q;
    
    out = 1'h0;
    M_alu16_a = 1'h0;
    M_alu16_b = 1'h0;
    M_alu16_alufn = alufn;
    
    case (M_test_q)
      INPUTA_test: begin
        if (switch[1+0-:1]) begin
          M_inputa_d = in;
          M_test_d = INPUTB_test;
        end else begin
          M_test_d = INPUTA_test;
        end
      end
      INPUTB_test: begin
        if (switch[0+0-:1]) begin
          M_inputb_d = in;
          M_test_d = OUTPUT_test;
        end else begin
          M_test_d = INPUTB_test;
        end
      end
      OUTPUT_test: begin
        M_alu16_a = M_inputa_q;
        M_alu16_b = M_inputb_q;
        out = M_alu16_out;
        M_test_d = OUTPUT_test;
      end
    endcase
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_inputa_q <= 1'h0;
      M_inputb_q <= 1'h0;
      M_test_q <= 1'h0;
    end else begin
      M_inputa_q <= M_inputa_d;
      M_inputb_q <= M_inputb_d;
      M_test_q <= M_test_d;
    end
  end
  
endmodule
