/*
   This file was generated automatically by Alchitry Labs version 1.2.1.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module shift16_8 (
    input [15:0] a,
    input [15:0] b,
    input [5:0] alufn,
    output reg [15:0] out
  );
  
  
  
  always @* begin
    
    case (alufn[0+2-:3])
      3'h0: begin
        out = a << b[0+3-:4];
      end
      3'h1: begin
        out = a >> b[0+3-:4];
      end
      3'h3: begin
        out = (a >> b[0+3-:4] | {5'h10{a[15+0-:1]}} << 5'h10 - b[0+3-:4]);
      end
      default: begin
        out = 16'h0000;
      end
    endcase
  end
endmodule
